import {
  BedDouble,
  CalendarCheck,
  CalendarDays,
  CalendarRange,
  FileText,
  Pill,
  UsersRound,
} from 'lucide-react'
import { Button } from '@/components/ui/button'
import { DataTable, type Cell } from '@/components/dhop/data-table'
import { PageHeader } from '@/components/dhop/page-header'

const reportTypes = [
  { icon: CalendarDays, label: 'Daily Summary', desc: 'Operational snapshot for the day' },
  { icon: CalendarRange, label: 'Weekly Summary', desc: 'Week-over-week performance' },
  { icon: FileText, label: 'Monthly Summary', desc: 'Full monthly review' },
  { icon: Pill, label: 'Medicine Inventory', desc: 'Stock levels and expiry' },
  { icon: BedDouble, label: 'Bed Occupancy', desc: 'Ward-wise bed utilization' },
  { icon: CalendarCheck, label: 'Attendance Report', desc: 'Staff attendance records' },
  { icon: UsersRound, label: 'Patient Summary', desc: 'OPD / IPD visit breakdown' },
]

const columns = ['Report', 'Type', 'Health Centre', 'Generated By', 'Generated At', 'Status']

const rows: Cell[][] = [
  ['Weekly Summary — W26', 'Weekly', 'PHC Rampur', 'Dr. S. Verma', 'Today, 09:12 AM', { badge: 'Ready', tone: 'success' }],
  ['Medicine Inventory — June', 'Inventory', 'PHC Rampur', 'A. Prasad', 'Yesterday, 04:40 PM', { badge: 'Ready', tone: 'success' }],
  ['Daily Summary — 04 Jul', 'Daily', 'CHC Sundarpur', 'Dr. K. Iyer', 'Yesterday, 06:05 PM', { badge: 'Ready', tone: 'success' }],
  ['Attendance — June', 'Attendance', 'CHC Bhairavi', 'Dr. R. Nair', '2 days ago', { badge: 'Ready', tone: 'success' }],
  ['Monthly Summary — June', 'Monthly', 'District Wide', 'District Admin', '3 days ago', { badge: 'Pending', tone: 'pending' }],
  ['Bed Occupancy — W25', 'Occupancy', 'District Hospital Central', 'Dr. A. Khan', '4 days ago', { badge: 'Ready', tone: 'success' }],
]

export default function ReportsPage() {
  return (
    <div className="flex flex-col gap-6">
      <PageHeader
        title="Reports"
        description="Generate and export operational reports."
        secondaryAction="Export All"
      />

      {/* Report type grid */}
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        {reportTypes.map((report) => (
          <div
            key={report.label}
            className="flex flex-col gap-3 rounded-lg border bg-card p-4 transition-colors hover:border-primary/40"
          >
            <div className="flex items-center gap-2.5">
              <span className="flex size-8 items-center justify-center rounded-lg bg-accent text-accent-foreground">
                <report.icon className="size-4" aria-hidden="true" />
              </span>
              <span className="text-sm font-medium">{report.label}</span>
            </div>
            <p className="text-xs text-muted-foreground">{report.desc}</p>
            <Button variant="outline" size="sm" className="mt-auto w-fit">
              Generate
            </Button>
          </div>
        ))}
      </div>

      <section className="flex flex-col gap-3">
        <h2 className="text-sm font-semibold">Recent Reports</h2>
        <DataTable
          columns={columns}
          rows={rows}
          filters={['Report Type', 'Health Centre', 'Date Range']}
          searchPlaceholder="Search reports..."
          emptyLabel="No reports generated yet."
          emptyAction="Generate Report"
        />
      </section>
    </div>
  )
}
