'use client';

import React, { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { toast } from 'sonner';
import { FileBarChart, Plus, Search, Download, ExternalLink, Calendar, Printer } from 'lucide-react';
import api from '@/lib/api';
import { useAuthStore } from '@/store/auth-store';
import { KpiCard } from '@/components/dhop/kpi-card';
import { StatusBadge } from '@/components/dhop/status-badge';
import { Drawer } from '@/components/dhop/drawer';
import { TableSkeleton } from '@/components/dhop/skeleton';
import { Button } from '@/components/ui/button';
import { exportToCSV } from '@/utils/export-utils';

const reportFormSchema = z.object({
  facilityId: z.string().nullable().optional(),
  reportType: z.enum(['Daily', 'Weekly', 'Monthly', 'Inventory', 'Attendance']),
  fileUrl: z.string().optional(),
});

type ReportFormData = z.infer<typeof reportFormSchema>;

export default function ReportsPage() {
  const queryClient = useQueryClient();
  const { user: currentUser } = useAuthStore();

  const [search, setSearch] = useState('');
  const [typeFilter, setTypeFilter] = useState<'ALL' | 'Daily' | 'Weekly' | 'Monthly' | 'Inventory' | 'Attendance'>('ALL');
  const [isCreateOpen, setIsCreateOpen] = useState(false);

  // Queries
  const { data: reports, isLoading, error } = useQuery<any[]>({
    queryKey: ['reports'],
    queryFn: async () => {
      const response = await api.get('/reports');
      return response.data?.data || [];
    },
  });

  const { data: healthCentres } = useQuery<any[]>({
    queryKey: ['health-centres-list-for-reports'],
    queryFn: async () => {
      const response = await api.get('/health-centres');
      return response.data?.data || [];
    },
  });

  const { data: staffList } = useQuery<any[]>({
    queryKey: ['staff-list-for-reports'],
    queryFn: async () => {
      const response = await api.get('/users');
      return response.data?.data || [];
    },
  });

  // Mutators
  const createMutation = useMutation({
    mutationFn: async (newReport: ReportFormData) => {
      const randomFileUrl =
        newReport.fileUrl ||
        `https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf`;
      const response = await api.post('/reports', {
        ...newReport,
        fileUrl: randomFileUrl,
        facilityId: newReport.facilityId || null,
      });
      return response.data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['reports'] });
      toast.success('Report generated successfully');
      setIsCreateOpen(false);
      reset();
    },
    onError: (err: any) => {
      toast.error(err.response?.data?.error?.message || 'Failed to generate report');
    },
  });

  // Forms setup
  const {
    register,
    handleSubmit,
    reset,
    formState: { errors },
  } = useForm<ReportFormData>({
    resolver: zodResolver(reportFormSchema),
    defaultValues: {
      reportType: 'Daily',
      facilityId: '',
    },
  });

  const onSubmitCreate = (data: ReportFormData) => {
    createMutation.mutate(data);
  };

  const filteredReports = (reports || []).filter((r) => {
    const matchesSearch = r.report_type.toLowerCase().includes(search.toLowerCase());
    const matchesType = typeFilter === 'ALL' || r.report_type === typeFilter;
    return matchesSearch && matchesType;
  });

  // Statistics calculation
  const totalReportsCount = reports?.length || 0;
  const recentReportsCount =
    reports?.filter(
      (r) =>
        r.created_at &&
        new Date(r.created_at) > new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    ).length || 0;

  const isAuthorized =
    currentUser?.role === 'DISTRICT_ADMIN' || currentUser?.role === 'FACILITY_ADMIN';

  if (error) {
    return (
      <div className="rounded-lg bg-destructive/10 p-6 text-center border border-destructive/20 max-w-lg mx-auto mt-12">
        <h2 className="text-lg font-semibold text-destructive">Database Connection Interrupted</h2>
        <p className="text-sm text-muted-foreground mt-2">
          Unable to retrieve reports data. Please verify backend API status and database configuration.
        </p>
      </div>
    );
  }

  const handlePrint = () => {
    window.print();
  };

  const handleExportExcel = () => {
    if (!filteredReports || filteredReports.length === 0) {
      toast.error('No report records to export');
      return;
    }
    const headers = ['Report Scope', 'Format', 'Generated By', 'Timestamp', 'Status'];
    const rows = filteredReports.map((r) => {
      const facilityName = healthCentres?.find((hc) => hc.id === r.facility_id)?.name || 'District-Wide';
      const staffName = staffList?.find((s) => s.id === r.generated_by)?.name || 'System';
      const timestamp = r.generated_at ? new Date(r.generated_at).toLocaleString() : '—';
      return [
        facilityName,
        r.report_type,
        staffName,
        timestamp,
        r.status,
      ];
    });
    exportToCSV('DHOP-Reports', headers, rows);
    toast.success('Reports list exported to CSV successfully');
  };

  return (
    <div className="flex flex-col gap-6">
      <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Reports</h1>
          <p className="text-sm text-muted-foreground">
            Generate and view periodic analytics, attendance charts, and inventory sheets.
          </p>
        </div>
        <div className="flex items-center gap-2 print:hidden">
          <Button onClick={handlePrint} variant="outline" size="sm" className="flex items-center gap-1">
            <Printer className="size-4" /> Print
          </Button>
          <Button onClick={handleExportExcel} variant="outline" size="sm" className="flex items-center gap-1">
            <Download className="size-4" /> Export CSV
          </Button>
          {isAuthorized && (
            <Button onClick={() => setIsCreateOpen(true)} size="sm" className="flex items-center gap-1.5">
              <Plus className="size-4" /> Generate Report
            </Button>
          )}
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
        <KpiCard label="Reports Stored" value={String(totalReportsCount)} icon={FileBarChart} />
        <KpiCard
          label="Generated This Week"
          value={String(recentReportsCount)}
          icon={Calendar}
          tone="success"
        />
      </div>

      {isLoading ? (
        <TableSkeleton cols={6} />
      ) : (
        <div className="flex flex-col gap-4">
          {/* Toolbar */}
          <div className="flex flex-col gap-2 sm:flex-row sm:items-center">
            <div className="relative flex-1 sm:max-w-xs">
              <Search
                className="absolute top-1/2 left-2.5 size-4 -translate-y-1/2 text-muted-foreground"
                aria-hidden="true"
              />
              <input
                type="search"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                placeholder="Search reports by type..."
                className="h-8 w-full rounded-lg border bg-card pr-3 pl-8 text-sm outline-none placeholder:text-muted-foreground focus-visible:ring-3 focus-visible:ring-ring/50"
              />
            </div>
            <div className="flex items-center gap-2 overflow-x-auto">
              {(['ALL', 'Daily', 'Weekly', 'Monthly', 'Inventory', 'Attendance'] as const).map((mode) => (
                <button
                  key={mode}
                  onClick={() => setTypeFilter(mode)}
                  className={`h-8 px-3 rounded-lg border text-xs font-medium whitespace-nowrap transition-colors ${
                    typeFilter === mode
                      ? 'bg-primary text-primary-foreground border-primary'
                      : 'bg-card text-muted-foreground hover:text-foreground'
                  }`}
                >
                  {mode === 'ALL' ? 'All Formats' : mode}
                </button>
              ))}
            </div>
          </div>

          {/* Table */}
          <div className="overflow-x-auto rounded-lg border bg-card">
            <table className="w-full min-w-max text-sm">
              <thead>
                <tr className="border-b bg-muted/50 text-left">
                  <th className="px-4 py-2.5 font-medium text-muted-foreground">Report Scope</th>
                  <th className="px-4 py-2.5 font-medium text-muted-foreground">Format</th>
                  <th className="px-4 py-2.5 font-medium text-muted-foreground">Generated By</th>
                  <th className="px-4 py-2.5 font-medium text-muted-foreground">Timestamp</th>
                  <th className="px-4 py-2.5 font-medium text-muted-foreground">Status</th>
                  <th className="w-24 px-4 py-2.5 text-right">Download</th>
                </tr>
              </thead>
              <tbody className="divide-y">
                {filteredReports.length === 0 ? (
                  <tr>
                    <td colSpan={6} className="text-center py-12 text-muted-foreground">
                      No reports generated yet.
                    </td>
                  </tr>
                ) : (
                  filteredReports.map((r) => {
                    const facilityName = healthCentres?.find((hc) => hc.id === r.facility_id)?.name;
                    const staffName = staffList?.find((s) => s.id === r.generated_by)?.name || 'System';
                    return (
                      <tr key={r.id} className="transition-colors hover:bg-muted/40">
                        <td className="px-4 py-3 font-medium whitespace-nowrap">
                          {r.facility_id ? (
                            facilityName || 'Facility Scoped'
                          ) : (
                            <span className="text-primary/70 font-semibold italic">District-Wide</span>
                          )}
                        </td>
                        <td className="px-4 py-3 whitespace-nowrap">
                          <StatusBadge tone="info">{r.report_type}</StatusBadge>
                        </td>
                        <td className="px-4 py-3 whitespace-nowrap text-xs text-muted-foreground">
                          {staffName}
                        </td>
                        <td className="px-4 py-3 whitespace-nowrap text-xs">
                          {r.generated_at ? new Date(r.generated_at).toLocaleString() : '—'}
                        </td>
                        <td className="px-4 py-3 whitespace-nowrap">
                          <StatusBadge tone={r.status === 'Completed' ? 'success' : 'critical'}>
                            {r.status}
                          </StatusBadge>
                        </td>
                        <td className="px-4 py-3 text-right whitespace-nowrap">
                          {r.file_url ? (
                            <a
                              href={r.file_url}
                              target="_blank"
                              rel="noopener noreferrer"
                              className="inline-flex items-center gap-1 text-xs text-primary font-medium hover:underline"
                            >
                              Open Link <ExternalLink className="size-3.5" />
                            </a>
                          ) : (
                            <span className="text-muted-foreground italic text-xs">Unavailable</span>
                          )}
                        </td>
                      </tr>
                    );
                  })
                )}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Generate Report Drawer */}
      <Drawer isOpen={isCreateOpen} onClose={() => setIsCreateOpen(false)} title="Compile Report Sheet">
        <form onSubmit={handleSubmit(onSubmitCreate)} className="flex flex-col gap-4">
          <div className="flex flex-col gap-1">
            <label className="text-xs font-semibold">Report Format *</label>
            <select
              {...register('reportType')}
              className="h-9 rounded-lg border bg-background px-3 text-sm outline-none focus-visible:ring-3 focus-visible:ring-ring/50"
            >
              <option value="Daily">Daily Summary</option>
              <option value="Weekly">Weekly Summary</option>
              <option value="Monthly">Monthly Summary</option>
              <option value="Inventory">Inventory Status</option>
              <option value="Attendance">Attendance Ledger</option>
            </select>
          </div>

          <div className="flex flex-col gap-1">
            <label className="text-xs font-semibold">Target Facility Scope</label>
            <select
              {...register('facilityId')}
              className="h-9 rounded-lg border bg-background px-3 text-sm outline-none focus-visible:ring-3 focus-visible:ring-ring/50"
            >
              <option value="">District-Wide (All Centres)</option>
              {healthCentres?.map((hc) => (
                <option key={hc.id} value={hc.id}>
                  {hc.name}
                </option>
              ))}
            </select>
            <p className="text-[10px] text-muted-foreground mt-0.5">
              Leave unselected to compile district-wide analytics.
            </p>
          </div>

          <div className="flex flex-col gap-1">
            <label className="text-xs font-semibold">PDF File URL (Optional)</label>
            <input
              {...register('fileUrl')}
              placeholder="https://..."
              className="h-9 rounded-lg border bg-background px-3 text-sm outline-none focus-visible:ring-3 focus-visible:ring-ring/50"
            />
            {errors.fileUrl && <span className="text-[10px] text-destructive">{errors.fileUrl.message}</span>}
          </div>

          <div className="flex justify-end gap-2 mt-4 pt-4 border-t">
            <Button type="button" variant="outline" onClick={() => setIsCreateOpen(false)}>
              Cancel
            </Button>
            <Button type="submit" disabled={createMutation.isPending}>
              {createMutation.isPending ? 'Generating...' : 'Compile PDF'}
            </Button>
          </div>
        </form>
      </Drawer>
    </div>
  );
}
